
app.service 'DataService', ($q, $http) ->
    teams: [
       {
          "name":"ArchitectControl",
          "rating":3,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Yuki Oda",
                "image":"https://secure.gravatar.com/avatar/a384292e7ec8bdcb77d74e786fbeb236?s=60&d=retro"
             },
             {
                "name":"Sean Voss",
                "image":"https://secure.gravatar.com/avatar/f2e4d42d67a226628325f4ed838841d4?s=60&d=retro"
             },
             {
                "name":"Petar Radosevic",
                "image":"https://secure.gravatar.com/avatar/d280fa9db61bc1d7d8a73f207511e346?s=60&d=retro"
             },
             {
                "name":"Greg Lindahl",
                "image":"https://secure.gravatar.com/avatar/a3ad4c29bc2aa53f457ac2a60d423850?s=60&d=retro"
             },
             {
                "name":"jason crilly",
                "image":"https://secure.gravatar.com/avatar/2655fbedb7024e990451065f4f8363d0?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"PowerCompression",
                "size":7,
                "languages":[
                   "PHP",
                   "Clojure",
                   "Ruby"
                ],
                "timeToComplete":14.779060633387417
             },
             {
                "name":"PageTart",
                "size":4,
                "languages":[
                   "Ruby",
                   "Scala",
                   "PHP",
                   "Javascript",
                   "CSS"
                ],
                "timeToComplete":15.322680985555053
             },
             {
                "name":"SymfonyDigital",
                "size":10,
                "languages":[
                   "CSS",
                   "PHP",
                   "Java",
                   "Javascript"
                ],
                "timeToComplete":0.3618144802749157
             },
             {
                "name":"PrepareNode",
                "size":10,
                "languages":[
                   "Ruby",
                   "Javascript",
                   "Obj-C",
                   "CSS",
                   "HTML"
                ],
                "timeToComplete":9.093210706487298
             },
             {
                "name":"WareBrew",
                "size":9,
                "languages":[
                   "Node.js",
                   "Obj-C",
                   "HTML",
                   "Obj-C"
                ],
                "timeToComplete":6.649491501040757
             },
             {
                "name":"ClientCake",
                "size":7,
                "languages":[
                   "Javascript",
                   "CSS",
                   "Javascript",
                   "Scala"
                ],
                "timeToComplete":4.051210176199675
             },
             {
                "name":"RouxFile",
                "size":6,
                "languages":[
                   "Obj-C",
                   "PHP",
                   "Ruby",
                   "Java",
                   "HTML"
                ],
                "timeToComplete":8.135460612829775
             },
             {
                "name":"PieMount",
                "size":8,
                "languages":[
                   "Node.js",
                   "HTML",
                   "PHP",
                   "Clojure",
                   "Node.js"
                ],
                "timeToComplete":20.822099652141333
             },
             {
                "name":"ProtocolPear",
                "size":10,
                "languages":[
                   "CSS",
                   "HTML",
                   "Javascript",
                   "Scala"
                ],
                "timeToComplete":34.737652568146586
             },
             {
                "name":"FumetGroup",
                "size":7,
                "languages":[
                   "CSS",
                   "PHP",
                   "Obj-C",
                   "HTML"
                ],
                "timeToComplete":25.667101594619453
             }
          ],
          "id":"64d7ccfea093f97b0ecc1d35702d0be6"
       },
       {
          "name":"OutputMill",
          "rating":3,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"CJ Winslow",
                "image":"https://secure.gravatar.com/avatar/8d4643514b9305ce3ac289288adb0b85?s=60&d=retro"
             },
             {
                "name":"Wataru Nishimoto",
                "image":"https://secure.gravatar.com/avatar/8091effddaad4c3713780911110184c9?s=60&d=retro"
             },
             {
                "name":"Maria Mobilia",
                "image":"https://secure.gravatar.com/avatar/250cfbda351931ed138f42ddf39fd53a?s=60&d=retro"
             },
             {
                "name":"Vivek Chopra",
                "image":"https://secure.gravatar.com/avatar/cc7de877a3440c204bfff41188de772c?s=60&d=retro"
             },
             {
                "name":"pairoj saksornyuth",
                "image":"https://secure.gravatar.com/avatar/0a7f6624478c3f6cb87fcd4e9ab44859?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"ScriptSyntax",
                "size":9,
                "languages":[
                   "CSS",
                   "Node.js",
                   "HTML",
                   "Obj-C"
                ],
                "timeToComplete":24.873646231368184
             },
             {
                "name":"LeakSpecialty",
                "size":4,
                "languages":[
                   "CSS",
                   "HTML",
                   "Clojure",
                   "Java",
                   "CSS"
                ],
                "timeToComplete":7.2112554823979735
             },
             {
                "name":"SymfonyViral",
                "size":1,
                "languages":[
                   "CSS",
                   "Javascript",
                   "Scala",
                   "Javascript"
                ],
                "timeToComplete":1.9828163348138332
             },
             {
                "name":"SaladAsynchronous",
                "size":3,
                "languages":[
                   "Java",
                   "Node.js",
                   "Java",
                   "CSS"
                ],
                "timeToComplete":0.063612618483603
             },
             {
                "name":"AlgorithmRestore",
                "size":5,
                "languages":[
                   "Ruby",
                   "CSS",
                   "Javascript",
                   "Ruby",
                   "CSS"
                ],
                "timeToComplete":3.675277659203857
             },
             {
                "name":"ITChip",
                "size":5,
                "languages":[
                   "HTML",
                   "Obj-C",
                   "CSS",
                   "Obj-C",
                   "Ruby"
                ],
                "timeToComplete":6.95931690861471
             },
             {
                "name":"FrameWeb",
                "size":10,
                "languages":[
                   "Scala",
                   "HTML",
                   "Java",
                   "CSS",
                   "Java"
                ],
                "timeToComplete":40.597154351416975
             },
             {
                "name":"CompressionSweet",
                "size":2,
                "languages":[
                   "HTML",
                   "Scala",
                   "CSS",
                   "Obj-C",
                   "Javascript"
                ],
                "timeToComplete":7.369427802041173
             },
             {
                "name":"HackerBuffet",
                "size":7,
                "languages":[
                   "Obj-C",
                   "HTML",
                   "Obj-C",
                   "Java",
                   "Obj-C"
                ],
                "timeToComplete":16.60812985850498
             },
             {
                "name":"PingOver",
                "size":2,
                "languages":[
                   "HTML",
                   "CSS",
                   "Ruby",
                   "Node.js"
                ],
                "timeToComplete":4.377230571582913
             }
          ],
          "id":"1965d15c045bd7b0039938e100d8a448"
       },
       {
          "name":"URLStem",
          "rating":5,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Eugenio Fuentefría",
                "image":"https://secure.gravatar.com/avatar/f28357f1d879bcc68a49d72865abc1bd?s=60&d=retro"
             },
             {
                "name":"Yoshinori Ueda",
                "image":"https://secure.gravatar.com/avatar/86f8b93ad9bdae5c92e755232aa23987?s=60&d=retro"
             },
             {
                "name":"martijn van der veen",
                "image":"https://secure.gravatar.com/avatar/649058438afa99889ac76d271cc09a5b?s=60&d=retro"
             },
             {
                "name":"Le Anh Tuan",
                "image":"https://secure.gravatar.com/avatar/58d8c2aef40a5d27a14db04ac66a9db8?s=60&d=retro"
             },
             {
                "name":"T T",
                "image":"https://secure.gravatar.com/avatar/955b72042c21e3808670aad7dc965595?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"ClusterFont",
                "size":6,
                "languages":[
                   "Ruby",
                   "Node.js",
                   "Java",
                   "Node.js",
                   "HTML"
                ],
                "timeToComplete":0.7734468067064881
             },
             {
                "name":"DressSystem",
                "size":5,
                "languages":[
                   "PHP",
                   "Ruby",
                   "Javascript",
                   "HTML",
                   "Ruby"
                ],
                "timeToComplete":13.310197892133147
             },
             {
                "name":"ThreadHybrid",
                "size":6,
                "languages":[
                   "HTML",
                   "PHP",
                   "CSS",
                   "PHP",
                   "CSS"
                ],
                "timeToComplete":3.595277185086161
             },
             {
                "name":"JasmineDev",
                "size":8,
                "languages":[
                   "Clojure",
                   "HTML",
                   "CSS",
                   "Java",
                   "Javascript"
                ],
                "timeToComplete":14.688679650425911
             },
             {
                "name":"VolumeDip",
                "size":5,
                "languages":[
                   "Node.js",
                   "Clojure",
                   "CSS",
                   "Node.js",
                   "Obj-C"
                ],
                "timeToComplete":14.890878106234595
             },
             {
                "name":"ClusterMince",
                "size":2,
                "languages":[
                   "Ruby",
                   "CSS",
                   "HTML",
                   "CSS",
                   "Node.js"
                ],
                "timeToComplete":6.749299226794392
             },
             {
                "name":"ChocolateRepository",
                "size":8,
                "languages":[
                   "Ruby",
                   "CSS",
                   "PHP",
                   "Node.js",
                   "HTML"
                ],
                "timeToComplete":7.276579579338431
             },
             {
                "name":"LogicDip",
                "size":7,
                "languages":[
                   "Obj-C",
                   "CSS",
                   "HTML",
                   "CSS",
                   "Clojure"
                ],
                "timeToComplete":21.81613604654558
             },
             {
                "name":"HTTPMega",
                "size":10,
                "languages":[
                   "Node.js",
                   "Java",
                   "HTML",
                   "Scala"
                ],
                "timeToComplete":23.403019765391946
             },
             {
                "name":"SeasonConsole",
                "size":2,
                "languages":[
                   "PHP",
                   "Node.js",
                   "PHP",
                   "Ruby",
                   "Java"
                ],
                "timeToComplete":3.0482384748756886
             }
          ],
          "id":"827c751c58d1535633e3891893a45c1c"
       },
       {
          "name":"FunctionKiwi",
          "rating":5,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Tonywilliam Kongsombat",
                "image":"https://secure.gravatar.com/avatar/755f8164bd0c54294f2ec82d7761c5d0?s=60&d=retro"
             },
             {
                "name":"Tobias Thiel",
                "image":"https://secure.gravatar.com/avatar/83e615d5fe43a8d073b6e85aa66eba0f?s=60&d=retro"
             },
             {
                "name":"Sho Takahashi",
                "image":"https://secure.gravatar.com/avatar/7c5cf7a828cce02090b2a5fc0a99dd38?s=60&d=retro"
             },
             {
                "name":"Will Tran",
                "image":"https://secure.gravatar.com/avatar/d846fef32e487fdb958fbce297f171d4?s=60&d=retro"
             },
             {
                "name":"Anirudh Koul",
                "image":"https://secure.gravatar.com/avatar/026acc1d82e79de340ed9eb1cdd46615?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"DevMill",
                "size":1,
                "languages":[
                   "CSS",
                   "PHP",
                   "CSS",
                   "Obj-C",
                   "CSS"
                ],
                "timeToComplete":1.4071008702740073
             },
             {
                "name":"MuffinCodec",
                "size":4,
                "languages":[
                   "Java",
                   "Clojure",
                   "HTML",
                   "Javascript",
                   "HTML"
                ],
                "timeToComplete":15.307535077445209
             },
             {
                "name":"ColumnTart",
                "size":6,
                "languages":[
                   "Node.js",
                   "Clojure",
                   "Java",
                   "Node.js",
                   "Java"
                ],
                "timeToComplete":14.274687620345503
             },
             {
                "name":"MemoryEncryption",
                "size":9,
                "languages":[
                   "Node.js",
                   "Clojure",
                   "Java",
                   "Obj-C"
                ],
                "timeToComplete":11.070676390081644
             },
             {
                "name":"SocketPigment",
                "size":5,
                "languages":[
                   "Javascript",
                   "Scala",
                   "Java",
                   "Ruby",
                   "HTML"
                ],
                "timeToComplete":6.47588322754018
             },
             {
                "name":"NodeQuiche",
                "size":8,
                "languages":[
                   "Obj-C",
                   "Ruby",
                   "PHP",
                   "Java",
                   "Obj-C"
                ],
                "timeToComplete":3.9636172726750374
             },
             {
                "name":"CloudNet",
                "size":9,
                "languages":[
                   "Node.js",
                   "Ruby",
                   "Java",
                   "Clojure",
                   "HTML"
                ],
                "timeToComplete":3.363813740434125
             },
             {
                "name":"CookeryRouter",
                "size":8,
                "languages":[
                   "CSS",
                   "Obj-C",
                   "Java",
                   "HTML",
                   "CSS"
                ],
                "timeToComplete":23.255596552044153
             },
             {
                "name":"ThreadSource",
                "size":6,
                "languages":[
                   "Javascript",
                   "HTML",
                   "Java",
                   "HTML"
                ],
                "timeToComplete":13.742380617186427
             },
             {
                "name":"ITCache",
                "size":6,
                "languages":[
                   "Ruby",
                   "Node.js",
                   "HTML",
                   "CSS",
                   "HTML"
                ],
                "timeToComplete":9.978016598615795
             }
          ],
          "id":"63cc9ee4ce7f7c15f49d634c564a73b2"
       },
       {
          "name":"PixelLegumes",
          "rating":1,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Sandeep Singh",
                "image":"https://secure.gravatar.com/avatar/afde149ec22f3f9fcb67d437c48c3c40?s=60&d=retro"
             },
             {
                "name":"Tyler Hamman",
                "image":"https://secure.gravatar.com/avatar/672db41e81d9b8d56dbef6da548c94f7?s=60&d=retro"
             },
             {
                "name":"Cosmo Wolfe",
                "image":"https://secure.gravatar.com/avatar/4a0078d8259c70110da566b81fa0ee0e?s=60&d=retro"
             },
             {
                "name":"saravana prabhu",
                "image":"https://secure.gravatar.com/avatar/5079c5cc84c6a51423dbdddb74ca723a?s=60&d=retro"
             },
             {
                "name":"Sophie Wong",
                "image":"https://secure.gravatar.com/avatar/d30edf0a70780f755f826fdccefd8188?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"GourmetRaw",
                "size":3,
                "languages":[
                   "HTML",
                   "Javascript",
                   "PHP",
                   "CSS"
                ],
                "timeToComplete":0.604309712536633
             },
             {
                "name":"StreamingFold",
                "size":6,
                "languages":[
                   "Clojure",
                   "Ruby",
                   "Java",
                   "CSS",
                   "Node.js"
                ],
                "timeToComplete":4.805489138234407
             },
             {
                "name":"CompressionPare",
                "size":1,
                "languages":[
                   "HTML",
                   "Scala",
                   "CSS",
                   "Java"
                ],
                "timeToComplete":2.870664776302874
             },
             {
                "name":"CommandJasmine",
                "size":10,
                "languages":[
                   "PHP",
                   "HTML",
                   "CSS",
                   "Javascript"
                ],
                "timeToComplete":35.39864994585514
             },
             {
                "name":"ProgrammersNet",
                "size":7,
                "languages":[
                   "Java",
                   "CSS",
                   "Ruby",
                   "HTML",
                   "Clojure"
                ],
                "timeToComplete":33.13102360465564
             },
             {
                "name":"EncryptionTender",
                "size":4,
                "languages":[
                   "HTML",
                   "CSS",
                   "Scala",
                   "Clojure",
                   "HTML"
                ],
                "timeToComplete":0.052076131105422974
             },
             {
                "name":"DeveloperPush",
                "size":1,
                "languages":[
                   "Java",
                   "HTML",
                   "CSS",
                   "Obj-C",
                   "Javascript"
                ],
                "timeToComplete":0.6129146320745349
             },
             {
                "name":"ComputingCaffeine",
                "size":6,
                "languages":[
                   "CSS",
                   "Ruby",
                   "Scala",
                   "Obj-C",
                   "HTML"
                ],
                "timeToComplete":6.231185768265277
             },
             {
                "name":"ParseBug",
                "size":9,
                "languages":[
                   "HTML",
                   "CSS",
                   "Scala",
                   "HTML"
                ],
                "timeToComplete":12.052554630674422
             },
             {
                "name":"PacketControl",
                "size":10,
                "languages":[
                   "Ruby",
                   "Javascript",
                   "HTML",
                   "Ruby",
                   "Node.js"
                ],
                "timeToComplete":25.06409988272935
             }
          ],
          "id":"e02edee0ba4f1622ad9f15ef26372112"
       },
       {
          "name":"SoupTag",
          "rating":5,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Nic Meliones",
                "image":"https://secure.gravatar.com/avatar/649ce5477ad21df59307ab9c7192a03b?s=60&d=retro"
             },
             {
                "name":"Jana Harper",
                "image":"https://secure.gravatar.com/avatar/0406dadab392e51ce10611ce49ae32a6?s=60&d=retro"
             },
             {
                "name":"Sumeet Rohatgi",
                "image":"https://secure.gravatar.com/avatar/bc6c2a857d3e864db554d1d5b89b4bec?s=60&d=retro"
             },
             {
                "name":"Sri Sonti",
                "image":"https://secure.gravatar.com/avatar/0426fb8f18c0ff16745f59af689b8237?s=60&d=retro"
             },
             {
                "name":"Pascal Manchon",
                "image":"https://secure.gravatar.com/avatar/d72e077047b1e055126d8faab057f165?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"VolumeHybrid",
                "size":10,
                "languages":[
                   "Obj-C",
                   "Node.js",
                   "Javascript",
                   "Clojure",
                   "CSS"
                ],
                "timeToComplete":12.840704154223204
             },
             {
                "name":"PacketCompression",
                "size":6,
                "languages":[
                   "HTML",
                   "Ruby",
                   "HTML",
                   "Node.js",
                   "HTML"
                ],
                "timeToComplete":6.65733473142609
             },
             {
                "name":"CoreTart",
                "size":9,
                "languages":[
                   "Obj-C",
                   "PHP",
                   "Ruby",
                   "PHP",
                   "Javascript"
                ],
                "timeToComplete":9.59714939002879
             },
             {
                "name":"QueueMousse",
                "size":4,
                "languages":[
                   "Java",
                   "CSS",
                   "Java",
                   "HTML",
                   "Java"
                ],
                "timeToComplete":1.8226501066237688
             },
             {
                "name":"CaffeinePixel",
                "size":9,
                "languages":[
                   "Ruby",
                   "CSS",
                   "Javascript",
                   "Ruby"
                ],
                "timeToComplete":29.483443337492645
             },
             {
                "name":"BotPan",
                "size":7,
                "languages":[
                   "Obj-C",
                   "Ruby",
                   "Obj-C",
                   "CSS"
                ],
                "timeToComplete":14.503660989925265
             },
             {
                "name":"ParseInduction",
                "size":8,
                "languages":[
                   "Ruby",
                   "HTML",
                   "Node.js",
                   "HTML",
                   "PHP"
                ],
                "timeToComplete":27.667461885139346
             },
             {
                "name":"ExceptionLean",
                "size":3,
                "languages":[
                   "CSS",
                   "Obj-C",
                   "Scala",
                   "Obj-C"
                ],
                "timeToComplete":11.861371147446334
             },
             {
                "name":"KernelSweet",
                "size":8,
                "languages":[
                   "Scala",
                   "CSS",
                   "Node.js",
                   "Scala"
                ],
                "timeToComplete":4.023359760642052
             },
             {
                "name":"WindowAddOn",
                "size":9,
                "languages":[
                   "Clojure",
                   "HTML",
                   "CSS",
                   "Javascript",
                   "CSS"
                ],
                "timeToComplete":15.943612495902926
             }
          ],
          "id":"0afbe930803d2f10f0be32fcf8f4b000"
       },
       {
          "name":"SmartNet",
          "rating":1,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Alicia Dixon",
                "image":"https://secure.gravatar.com/avatar/5820b54730081a36258a0e62a42cbbdc?s=60&d=retro"
             },
             {
                "name":"Fredrick Thornton",
                "image":"https://secure.gravatar.com/avatar/6c332528bb73d5f0f5b1872cf7ff8e48?s=60&d=retro"
             },
             {
                "name":"Stefan Mirea",
                "image":"https://secure.gravatar.com/avatar/60fd9553c591350bc0514b6eb00131e0?s=60&d=retro"
             },
             {
                "name":"Samer Masry",
                "image":"https://secure.gravatar.com/avatar/7385e2ac333b8b72623ace6d241862b0?s=60&d=retro"
             },
             {
                "name":"Rangel Spasov",
                "image":"https://secure.gravatar.com/avatar/21e914daf7364413cb953b8190d7ddff?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"PestoSmart",
                "size":5,
                "languages":[
                   "Clojure",
                   "Java",
                   "CSS",
                   "HTML",
                   "CSS"
                ],
                "timeToComplete":3.1800088880117983
             },
             {
                "name":"BotSoft",
                "size":1,
                "languages":[
                   "CSS",
                   "Ruby",
                   "PHP",
                   "Node.js",
                   "Obj-C"
                ],
                "timeToComplete":3.387451944872737
             },
             {
                "name":"EngineCore",
                "size":4,
                "languages":[
                   "CSS",
                   "Obj-C",
                   "HTML",
                   "Javascript",
                   "Ruby"
                ],
                "timeToComplete":13.07863425463438
             },
             {
                "name":"HoneyArchitect",
                "size":4,
                "languages":[
                   "HTML",
                   "Obj-C",
                   "Javascript",
                   "HTML",
                   "Ruby"
                ],
                "timeToComplete":3.832625807262957
             },
             {
                "name":"RouxComputing",
                "size":10,
                "languages":[
                   "Obj-C",
                   "CSS",
                   "HTML",
                   "PHP",
                   "Ruby"
                ],
                "timeToComplete":37.76743868365884
             },
             {
                "name":"CompileCommand",
                "size":8,
                "languages":[
                   "Node.js",
                   "PHP",
                   "Node.js",
                   "Obj-C"
                ],
                "timeToComplete":17.935695990920067
             },
             {
                "name":"WebPlum",
                "size":2,
                "languages":[
                   "PHP",
                   "CSS",
                   "Javascript",
                   "HTML"
                ],
                "timeToComplete":4.1962449587881565
             },
             {
                "name":"CyberOver",
                "size":1,
                "languages":[
                   "HTML",
                   "Java",
                   "CSS"
                ],
                "timeToComplete":1.314689423656091
             },
             {
                "name":"ConstantChef",
                "size":6,
                "languages":[
                   "HTML",
                   "Node.js",
                   "Obj-C",
                   "Node.js",
                   "HTML"
                ],
                "timeToComplete":16.414707920048386
             },
             {
                "name":"ClusterAsynchronous",
                "size":5,
                "languages":[
                   "Ruby",
                   "Javascript",
                   "Ruby",
                   "Javascript"
                ],
                "timeToComplete":17.04679310321808
             }
          ],
          "id":"5f1dfd7917344f4ff506089244fd847a"
       },
       {
          "name":"SpecialtyPort",
          "rating":4,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Sibon Li",
                "image":"https://secure.gravatar.com/avatar/0ae286c09d429f38fd3e5bd03a3e2f3f?s=60&d=retro"
             },
             {
                "name":"Shuichi Tsutsumi",
                "image":"https://secure.gravatar.com/avatar/19d7ae634445d4bd9b10c7961a462260?s=60&d=retro"
             },
             {
                "name":"Shrav Mehta",
                "image":"https://secure.gravatar.com/avatar/ca93e1d1f209e9c4158eed46d834d678?s=60&d=retro"
             },
             {
                "name":"Anatoly Sharifulin",
                "image":"https://secure.gravatar.com/avatar/71aabd7c0553dd548a49a09a0e4698ff?s=60&d=retro"
             },
             {
                "name":"Shakul Hameed",
                "image":"https://secure.gravatar.com/avatar/71752e1c592b1ba799f48690711579f2?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"PushFrame",
                "size":9,
                "languages":[
                   "CSS",
                   "Clojure",
                   "CSS",
                   "Ruby",
                   "Java"
                ],
                "timeToComplete":9.125292696990073
             },
             {
                "name":"ExportRosemary",
                "size":2,
                "languages":[
                   "Javascript",
                   "Ruby",
                   "CSS",
                   "Java"
                ],
                "timeToComplete":2.4693816639482975
             },
             {
                "name":"BooleanCodec",
                "size":8,
                "languages":[
                   "HTML",
                   "Ruby",
                   "HTML",
                   "CSS"
                ],
                "timeToComplete":12.399584837257862
             },
             {
                "name":"WokRouter",
                "size":5,
                "languages":[
                   "Javascript",
                   "PHP",
                   "CSS",
                   "HTML",
                   "Ruby"
                ],
                "timeToComplete":22.367422201205045
             },
             {
                "name":"SymfonyRestore",
                "size":6,
                "languages":[
                   "HTML",
                   "Node.js",
                   "CSS"
                ],
                "timeToComplete":3.9324393589049578
             },
             {
                "name":"BaseTasting",
                "size":10,
                "languages":[
                   "HTML",
                   "CSS",
                   "HTML",
                   "CSS",
                   "Ruby"
                ],
                "timeToComplete":33.776455419138074
             },
             {
                "name":"DeveloperMail",
                "size":3,
                "languages":[
                   "HTML",
                   "CSS",
                   "Javascript",
                   "HTML",
                   "Obj-C"
                ],
                "timeToComplete":3.6654137691948563
             },
             {
                "name":"ExtensionStuff",
                "size":9,
                "languages":[
                   "CSS",
                   "HTML",
                   "Java"
                ],
                "timeToComplete":4.873567208647728
             },
             {
                "name":"SessionTool",
                "size":5,
                "languages":[
                   "CSS",
                   "HTML",
                   "Node.js",
                   "Obj-C"
                ],
                "timeToComplete":16.36446814518422
             },
             {
                "name":"CompressionWeb",
                "size":1,
                "languages":[
                   "CSS",
                   "HTML",
                   "Obj-C",
                   "PHP",
                   "CSS"
                ],
                "timeToComplete":3.406048695323989
             }
          ],
          "id":"1926d1111611ac2f422147d382fc580e"
       },
       {
          "name":"BootChop",
          "rating":3,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Melody Schaeffer",
                "image":"https://secure.gravatar.com/avatar/2ce12fb93a0543c993c566ae5fdcce9e?s=60&d=retro"
             },
             {
                "name":"Sarah Kennedy",
                "image":"https://secure.gravatar.com/avatar/79d2acc9201f41a398b37bac6b528235?s=60&d=retro"
             },
             {
                "name":"Sarah Austin",
                "image":"https://secure.gravatar.com/avatar/2053f5ff84ac603c7ca94c7a5b6aeeed?s=60&d=retro"
             },
             {
                "name":"Sanja Plohl",
                "image":"https://secure.gravatar.com/avatar/f9fbc8475e7830697068019ccaaab583?s=60&d=retro"
             },
             {
                "name":"Sandy Le",
                "image":"https://secure.gravatar.com/avatar/02d1496f0812a914bd2c3aa7c18c5499?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"TapeCache",
                "size":8,
                "languages":[
                   "Scala",
                   "CSS",
                   "HTML",
                   "Node.js"
                ],
                "timeToComplete":11.586145177483559
             },
             {
                "name":"GroupLink",
                "size":8,
                "languages":[
                   "Javascript",
                   "CSS",
                   "HTML",
                   "CSS",
                   "HTML"
                ],
                "timeToComplete":9.831525953486562
             },
             {
                "name":"PixelTasting",
                "size":3,
                "languages":[
                   "HTML",
                   "Obj-C",
                   "Javascript",
                   "HTML",
                   "Ruby"
                ],
                "timeToComplete":14.125299226725474
             },
             {
                "name":"FontBoil",
                "size":7,
                "languages":[
                   "Clojure",
                   "Obj-C",
                   "HTML"
                ],
                "timeToComplete":20.734376854263246
             },
             {
                "name":"ExtensionSample",
                "size":9,
                "languages":[
                   "Java",
                   "HTML",
                   "CSS",
                   "Node.js",
                   "Java"
                ],
                "timeToComplete":12.490197048755363
             },
             {
                "name":"BlendCharacter",
                "size":7,
                "languages":[
                   "CSS",
                   "Javascript",
                   "CSS",
                   "Javascript",
                   "CSS"
                ],
                "timeToComplete":11.938218077411875
             },
             {
                "name":"BootSession",
                "size":4,
                "languages":[
                   "Obj-C",
                   "Scala",
                   "Node.js"
                ],
                "timeToComplete":11.133908369578421
             },
             {
                "name":"ExploitMarinate",
                "size":4,
                "languages":[
                   "Javascript",
                   "HTML",
                   "Java",
                   "CSS",
                   "Ruby"
                ],
                "timeToComplete":1.4764968026429415
             },
             {
                "name":"HTTPPie",
                "size":2,
                "languages":[
                   "Scala",
                   "Ruby",
                   "HTML",
                   "Node.js"
                ],
                "timeToComplete":5.626418659463525
             },
             {
                "name":"WikiBouchees",
                "size":9,
                "languages":[
                   "Obj-C",
                   "Java",
                   "CSS",
                   "Javascript",
                   "HTML"
                ],
                "timeToComplete":30.42627526796423
             }
          ],
          "id":"ec43b576efe30ac39202e57305c54ce7"
       },
       {
          "name":"CookeryEmulation",
          "rating":2,
          "image":"http://thecatapi.com/api/images/get?size=small&type=png,jpg",
          "members":[
             {
                "name":"Jean-Pierre Pequito",
                "image":"https://secure.gravatar.com/avatar/ffe6c4de9930035ff8c9894790e4cb8b?s=60&d=retro"
             },
             {
                "name":"Saket Saurabh",
                "image":"https://secure.gravatar.com/avatar/5d6aacd9fc0fb3ec774520db7c0c0417?s=60&d=retro"
             },
             {
                "name":"Rodolfo Ruiz",
                "image":"https://secure.gravatar.com/avatar/f41e47b189d9d45ec6e5a6f05b3535f3?s=60&d=retro"
             },
             {
                "name":"Rolly Rulete",
                "image":"https://secure.gravatar.com/avatar/10694e6ae448101faa48d4cdd84a032f?s=60&d=retro"
             },
             {
                "name":"Ricky Chu",
                "image":"https://secure.gravatar.com/avatar/97c867dc110ff97e40a7d9ee5f6adaca?s=60&d=retro"
             }
          ],
          "projects":[
             {
                "name":"BaseKiwi",
                "size":5,
                "languages":[
                   "Obj-C",
                   "Ruby",
                   "CSS",
                   "Java"
                ],
                "timeToComplete":10.28994143474847
             },
             {
                "name":"CoulisDeprecated",
                "size":9,
                "languages":[
                   "Ruby",
                   "CSS",
                   "HTML",
                   "CSS",
                   "Javascript"
                ],
                "timeToComplete":26.6275426663924
             },
             {
                "name":"OverPesto",
                "size":5,
                "languages":[
                   "CSS",
                   "HTML",
                   "Javascript",
                   "PHP",
                   "HTML"
                ],
                "timeToComplete":7.954547234112397
             },
             {
                "name":"BooleanMix",
                "size":6,
                "languages":[
                   "Java",
                   "Obj-C",
                   "CSS",
                   "Obj-C",
                   "HTML"
                ],
                "timeToComplete":22.311465041711926
             },
             {
                "name":"PateDevice",
                "size":6,
                "languages":[
                   "Obj-C",
                   "Ruby",
                   "Node.js",
                   "Obj-C",
                   "Java"
                ],
                "timeToComplete":20.011137526016682
             },
             {
                "name":"PingOlive",
                "size":10,
                "languages":[
                   "CSS",
                   "Java",
                   "Node.js",
                   "Scala",
                   "CSS"
                ],
                "timeToComplete":30.905208131298423
             },
             {
                "name":"CacheBug",
                "size":8,
                "languages":[
                   "Java",
                   "Ruby",
                   "PHP",
                   "Ruby",
                   "Node.js"
                ],
                "timeToComplete":9.811350889503956
             },
             {
                "name":"NavigationSpecialty",
                "size":4,
                "languages":[
                   "CSS",
                   "Ruby",
                   "CSS",
                   "PHP",
                   "Node.js"
                ],
                "timeToComplete":15.835501048713923
             },
             {
                "name":"CircuitPower",
                "size":2,
                "languages":[
                   "Node.js",
                   "PHP",
                   "Clojure",
                   "Scala",
                   "Node.js"
                ],
                "timeToComplete":0.2838643454015255
             },
             {
                "name":"PlateSocket",
                "size":4,
                "languages":[
                   "Javascript",
                   "HTML",
                   "CSS",
                   "HTML",
                   "Ruby"
                ],
                "timeToComplete":8.833241476677358
             }
          ],
          "id":"32def893d8ee0b7fd63e2a3641b666fe"
       }
    ]